apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: easy-circulars-dataprep-deployment
  name: easy-circulars-dataprep-deployment
  namespace: easy-circulars
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: easy-circulars-dataprep-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: easy-circulars-dataprep-deployment
    spec:
      nodeSelector:
        kubernetes.io/hostname: g2-r1-2
      containers:
        - env:
            - name: HTTPS_PROXY
              value: http://proxy-dmz.intel.com:912
            - name: HTTP_PROXY
              value: http://proxy-dmz.intel.com:912
            - name: HUGGINGFACEHUB_API_TOKEN
              value: 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
            - name: LLM_SERVER_HOST_IP
              value: easy-circulars-groq-deployment
            - name: LLM_SERVER_PORT
              value: "5101"
            - name: LOGFLAG
              value: "true"
            - name: REDIS_URL
              value: redis://easy-circulars-redis-deployment:6381
            - name: TEI_EMBEDDING_ENDPOINT
              value: http://easy-circulars-embedding-service-deployment:6010
            - name: http_proxy
              value: http://proxy-dmz.intel.com:912
            - name: https_proxy
              value: http://proxy-dmz.intel.com:912
            - name: no_proxy
              value: 127.0.0.1,localhost,.intel.com,easy-circulars-redis-deployment,easy-circulars-groq-deployment
          image: navchetna/dataprep:latest
          name: easy-circulars-dataprep-container
          ports:
            - containerPort: 6007
              protocol: TCP
          volumeMounts:
            - mountPath: ~/.cache/huggingface/hub
              name: easy-circulars-tei-reranking-claim0
      restartPolicy: Always
      volumes:
        - name: easy-circulars-tei-reranking-claim0
          hostPath:
            path: /mnt/hf_cache
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: easy-circulars-dataprep-deployment
  name: easy-circulars-dataprep-deployment
  namespace: easy-circulars
spec:
  type: NodePort
  ports:
    - name: "5012"
      port: 5012
      protocol: TCP
      targetPort: 6007
      nodePort: 30012
  selector:
    io.kompose.service: easy-circulars-dataprep-deployment