apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: easy-circulars-groq-deployment
  name: easy-circulars-groq-deployment
  namespace: easy-circulars
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: easy-circulars-groq-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: easy-circulars-groq-deployment
    spec:
      nodeSelector:
        kubernetes.io/hostname: g2-r1-2
      containers:
        - env:
            - name: GROQ_API_KEY
              value: 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
            - name: HTTPS_PROXY
              value: http://proxy-dmz.intel.com:912
            - name: HTTP_PROXY
              value: http://proxy-dmz.intel.com:912
            - name: http_proxy
              value: http://proxy-dmz.intel.com:912
            - name: https_proxy
              value: http://proxy-dmz.intel.com:912
            - name: no_proxy
              value: 127.0.0.1,localhost,.intel.com
          image: navchetna/groq:latest
          name: easy-circulars-groq-container
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: ~/.cache/huggingface/hub
              name: easy-circulars-tei-reranking-claim0
      restartPolicy: Always
      volumes:
        - name: easy-circulars-tei-reranking-claim0
          hostPath:
            path: /mnt/hf_cache
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: easy-circulars-groq-deployment
  name: easy-circulars-groq-deployment
  namespace: easy-circulars
spec:
  type: NodePort
  ports:
    - name: "5101"
      port: 5101
      protocol: TCP
      targetPort: 8000
      nodePort: 30004
  selector:
    io.kompose.service: easy-circulars-groq-deployment