apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: easy-circulars-webscraper-deployment
  name: easy-circulars-webscraper-deployment
  namespace: easy-circulars
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: easy-circulars-webscraper-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: easy-circulars-webscraper-deployment
    spec:
      nodeSelector:
        kubernetes.io/hostname: g2-r1-2
      containers:
        - env:
            - name: SERVER_HOST_IP
              value: easy-circulars-backend-deployment
            - name: SERVER_PORT
              value: "5013"
            - name: DATAPREP_HOST_IP
              value: easy-circulars-dataprep-deployment
            - name: DATAPREP_PORT
              value: "5012"
            - name: HTTPS_PROXY
              value: http://proxy-dmz.intel.com:912
            - name: HTTP_PROXY
              value: http://proxy-dmz.intel.com:912
            - name: http_proxy
              value: http://proxy-dmz.intel.com:912
            - name: https_proxy
              value: http://proxy-dmz.intel.com:912
            - name: no_proxy
              value: 127.0.0.1,localhost,.intel.com,easy-circulars-dataprep-deployment,easy-circulars-backend-deployment
          image: navchetna/easy-circulars-webscraper:latest
          name: easy-circulars-webscraper-container
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /home/user/ui
              name: pdfs
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /home/intel/easy-circulars/ui
          name: pdfs
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: easy-circulars-webscraper-deployment
  name: easy-circulars-webscraper-deployment
  namespace: easy-circulars
spec:
  type: NodePort
  ports:
    - name: "5102"
      port: 5102
      protocol: TCP
      targetPort: 8002
      nodePort: 30017
  selector:
    io.kompose.service: easy-circulars-webscraper-deployment