# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
# 5d081333-2c77-414d-b218-632d488b353d
version: "3.8"

services:
  easy-circulars-redis:
    image: redis/redis-stack:7.2.0-v9
    container_name: easy-circulars-redis
    ports:
      - "6381:6379"
      - "8002:8001"  
      
  easy-circulars-mongodb:
    image: mongo
    container_name: easy-circulars-mongodb
    restart: always
    ports:
      - "27018:27017"

  easy-circulars-groq:
    image: easy-circulars/groq:latest
    container_name: easy-circulars-groq
    ports:
      - "5101:8000"
    volumes:
      - "./cache:/root/.cache"
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      GROQ_API_KEY: ${GROQ_API_KEY}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}

  easy-circulars-webscraper:
    image: easy-circulars/webscraper:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: easy-circulars-webscraper
    ports:
      - "5102:8002"
    volumes:
      - ${UI_DIR}:/home/user/ui
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      SERVER_HOST_IP: ${SERVER_HOST_IP}
      SERVER_PORT: ${SERVER_PORT}     
      DATAPREP_HOST_IP: ${DATAPREP_HOST_IP}
      DATAPREP_PORT: ${DATAPREP_PORT}    
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}

  easy-circulars-tei-reranking:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.5
    container_name: easy-circulars-tei-reranking
    ports:
      - "8810:80"
    volumes:
      - "./data:/data"
    shm_size: 1g
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
      HF_HUB_DISABLE_PROGRESS_BARS: 1
      HF_HUB_ENABLE_HF_TRANSFER: 0
    command: --model-id ${RERANK_MODEL_ID} --auto-truncate

  easy-circulars-embedding-service:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.5
    container_name: easy-circulars-embedding-service
    ports:
      - "6010:80"
    volumes:
      - "./data:/data"
    shm_size: 1g
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
    command: --model-id ${EMBEDDING_MODEL_ID} --auto-truncate

  easy-circulars-retriever:
    image: easy-circulars/retriever:latest
    container_name: easy-circulars-retriever
    ports:
      - "5011:7000"
    ipc: host
    depends_on:
      - easy-circulars-redis
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      REDIS_URL: ${REDIS_URL}
      INDEX_NAME: ${INDEX_NAME}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      TEI_EMBEDDING_ENDPOINT: http://easy-circulars-embedding-service:80
      HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
    restart: unless-stopped

networks:
  default:
    driver: bridge
